# Generated by Django 5.0.4 on 2024-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_details_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='approve',
            field=models.IntegerField(default=0),
        ),
    ]
